version: '3.8'

services:
  mx-simplon-api:
    build: .
    container_name: mx-simplon-api
    environment:
      ZMQ_ADDRESS: tcp://*:5555
      #To access the masterfile, you can either copy it to the container by modifying
      # the dockerfile, or you can mount a volume containing the masterfile.
      HDF5_MASTER_FILE: /path/to/HDF5_master_file
      DELAY_BETWEEN_FRAMES: 0.0 # seconds
      NUMBER_OF_DATA_FILES: 1 # 2 seems to be the maximum number of files we can load into memory (16M data)
      NUMBER_OF_FRAMES_PER_TRIGGER: 30
    ports:
      - "8000:8000"
      - "5555:5555"
