version: '3.8'

services:
  mxsimplonapi:
    build: .
    container_name: mxsimplonapi
    environment:
      ZMQ_ADDRESS: tcp://*:5555
      HDF5_MASTER_FILE: /share_data/datasets_full/17831a/0019/testcrystal_0019_master.h5
      DELAY_BETWEEN_FRAMES: 0.001 # seconds
      COMPRESSION_TYPE: bslz4 # allowed options are: lz4, bslz4, or no_compression
      NUMBER_OF_DATA_FILES: 2 # 2 seems to be the maximum number of files we can load into memory (16M data)
      NUMBER_OF_FRAMES_PER_TRIGGER: 400 # A number multiple of 200
      RASTER_FRAMES: "False" # can be True or False
    ports:
      - "8000:8000"
      - "5555:5555"
    volumes:
      - simplon_share_data:/share_data

volumes:
  simplon_share_data:
    driver: local
    driver_opts:
      type: cifs
      device: //10.244.101.66/smd-share
      o: username=guest,password=guest,vers=2.0,uid=1000,gid=1000

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
