[tool.poetry]
name = "ansto-simplon-api"
version = "0.2.0"
description = "Simulated simplon api"
authors = ["Francisco Hernandez Vivanco <hernandf@ansto.gov.au>",
           "Daniel Eriksson <daniele@ansto.gov.au>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "0.103.0"
numpy = "1.25.2"
pyzmq = "25.1.1"
h5py = "3.9.0"
hdf5plugin = "4.1.3"
uvicorn = "0.23.2"
lz4 = "4.3.2"
tqdm = "4.63.0"
cbor2 = "5.4.6"
bitshuffle = "0.5.1"
requests = "2.31.0"
dectris-compression = "^0.2.3"

[tool.poetry.dev-dependencies]
pre-commit = "^2.17.0"
flake8 = "^4.0.1"
black = "^22.1.0"
isort = "^5.10.1"

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
